version: '3.8'

services:
  # ----------------------------------------------------------------
  # 1. DATABASE (PostgreSQL + pgvector)
  # ----------------------------------------------------------------
  db:
    image: pgvector/pgvector:pg16
    container_name: elearning-platform_db
    restart: always
    environment:
      POSTGRES_USER: admin       
      POSTGRES_PASSWORD: admin   
      POSTGRES_DB: elearning-platform_db     
    ports:
      - "5432:5432"              
    volumes:
      - postgres_data:/var/lib/postgresql/data # Giữ dữ liệu không bị mất khi tắt máy

  # ----------------------------------------------------------------
  # 2. AI SERVICE (Python RAG)
  # ----------------------------------------------------------------
  rag:
    build: ./rag          
    container_name: rag_python
    ports:
      - "8000:8000"              # Mở cổng API cho bên ngoài test
    environment:
      - DATABASE_URL=postgresql+psycopg2://admin:admin@db:5432/elearning-platform_db
    env_file:
      - ./rag/.env        # Lấy Google Key từ file .env
    volumes:
      - ./rag:/app        
      - /app/venv
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

volumes:
  postgres_data: